<?php

$this->category = 'offers';
$this->page = 'createOffers';
$this->breadCrumbs = array(
	array('title'=>'Admin', 'url'=>'/admin'),
	array('title'=>'Offers', 'url'=>'/admin/offers'),
	array('title'=>"Create Offer", 'url'=>$this->url())
);



$resetLink = $this->url(array('time' => time()));

if($this->company) {
	$companyLink = $this->url(array(
		'controller'	=> 'companies',
		'action'		=> 'edit',
		'id'			=> $this->company->id
	)) . '#&tab-offers';

	$this->breadCrumbs = array(
			array('title'=>'Admin', 							'url'=>'/admin'),
			array('title'=>'Companies', 						'url'=>'/admin/companies'),
			array('title'=>"Company ({$this->company->name}) ", 'url'=>$companyLink),
			array('title'=>"Create Offer", 				'url'=>$this->url())
	);

	$backButton = <<<HTML
		<button onclick="window.location='$companyLink'" type="button">
			<img src="/skins/admin/assets/img/icons/fugue/navigation-180.png" width="16" height="16"> Back to company
		</button>
HTML;
} else {
	$backButton = <<<HTML
		<button onclick="window.location='/admin/offers/browse'" type="button">
			<img src="/skins/admin/assets/img/icons/fugue/navigation-180.png" width="16" height="16"> Back to list
		</button>
HTML;
}






$this->controlBar = <<<HTML
<div id="control-bar" class="grey-bg clearfix" style="opacity: 1; ">
	<div class="container_12">
		<div class="float-left">
			{$backButton}
		</div>

		<div class="float-right">
			<button onclick="window.location='/admin/offers/browse'" type="button" class="red">Cancel</button>
			<button type="button" onclick="window.location='$resetLink'" class="grey">Reset</button>
			<button type="button" onclick="$('#complex_form').submit()"><img src="/skins/admin/assets/img/icons/fugue/tick-circle.png" width="16" height="16"> Save New Offer</button>
		</div>
	</div>
</div>
HTML;
?>


<? if($this->saveSuccess): ?>
<ul class="message success grid_12">
	<li>Offer saved  <strong>successfully</strong>.</li>
	<li class="close-bt"></li>
</ul>
<? elseif($this->saveError): ?>
<ul class="message error grid_12">
	<li>Save was <strong>not successfully</strong>, please correct the errors below.</li>
	<li class="close-bt"></li>
</ul>
<? endif; ?>

<section class="grid_12">
	<div class="block-border"><form class="block-content form" id="complex_form" method="post" action="">
		<h1>New Offer</h1>

		<div class="block-controls">
			<ul class="controls-tabs js-tabs">
				<li class="current">
					<a href="#" title="Offer Settings">
						<img src="/skins/admin/assets/img/icons/web-app/24/Add.png" width="24" height="24"/>
					</a>
				</li>
			</ul>
		</div>


		<div class="columns">
			<div class="col200pxL-left">
				<h2>Offer Settings</h2>
				<ul class="side-tabs js-tabs same-height">
					<li><a href="#tab-settings" title="Setting">Settings</a></li>
					<li><a href="#tab-description" title="Setting">Description</a></li>
					<li><a href="#tab-highlights" title="Highlights">Highlights</a></li>
					<li><a href="#tab-fine-print" title="Fine Print">Fine Print</a></li>
				</ul>

			</div>
			<div class="col200pxL-right">
				<?=$this->form;?>
			</div>
		</div>
	</form></div>
</section>


