<?php

$this->headTitle('Registration Complete');
$user = GTW_Service_User::getInstance()->getCurrentUser();

?>



<div class="content-box" style="width:740px;">
	<table width="100%" cellpadding="0" cellspacing="0" border="0">
		<tr class="header">
			<td class="left"></td>
			<td class="center" width="802"></td>
			<td class="right"></td>
		</tr>
		<tr>
			<td class="title" colspan="3" style="padding:20px;">
				<h1>Registration Complete</h1>
			</td>
		</tr>
		<tr>
			<td colspan="3" class="body" style="
				padding-top:20px;
				padding-bottom:40px;
				padding-left:80px;
				padding-right:80px;
				text-align: left;">

				<h3>Thanks signing up!</h3><hr style='border:1px dotted;' /><br />
				<p>We'll do our best to deliver you great deals in your local area. Also giving you a feel good, win/win way to support charities close to home as well as world wide charities.</p>
				<br />
				<h3>Your now logged in!</h3><hr style='border:1px dotted;' /><br />
				<p>If you look on the left side of your screen you will notice the account and login links. Account lets you modify your subscriptions and access/edit any of your information and coupons/donations.</p>
				
				<h3>Please confirm your email address!</h3><hr style='border:1px dotted;' /><br />
				<p>We have sent you a email to that address(<?=$user->email;?>) With an activation code. Your account won't have full access to Give to Win until you have confirmed your email address.</p>
				<br />
			</td>
		</tr>
	</table>
</div>