<?php

$this->layout()->setLayout('minimal');
$this->bodyClasses = 'special-page login-bg dark';
$this->headTitle('Login - ', 'PREPEND');

$this->headScript()->prependFile('/skins/admin/assets/js/mini.php?files=gc/login,jquery.zend.jsonrpc');
$this->headScript()->appendFile('/skins/admin/assets/js/gtw/login.js');

?>


<section id="login-block">
		<div class="block-border"><div class="block-content">

			<!--
			IE7 compatibility: if you want to remove the <h1>,
			add style="zoom:1" to the above .block-content div
			-->
			<h1>Ver <?=GTW_VERSION;?></h1>
			<div class="block-header">GTW Admin Login</div>

			<form class="form with-margin" action="/admin/auth/login-json" name="login-form" id="login-form" method="post" action="">
				<input type="hidden" name="a" id="a" value="send">
				<p class="inline-small-label">
					<label for="login"><span class="big">Email</span></label>
					<input type="text" name="login" id="login" class="full-width" value="sean@skyseek.com">
				</p>
				<p class="inline-small-label">
					<label for="pass"><span class="big">Password</span></label>
					<input type="password" name="pass" id="pass" class="full-width" value="blackdog">
				</p>

				<button type="submit" class="float-right">Login</button>

				<!--
				<p class="input-height">
					<input type="checkbox" name="keep-logged" id="keep-logged" value="1" class="mini-switch" checked="checked">
					<label for="keep-logged" class="inline">Keep me logged in</label>
				</p>
				-->
				<div style="clear:both;" />
			</form>
			<!--
			<form class="form" id="password-recovery" method="post" action="">
				<fieldset class="grey-bg no-margin collapse">
					<legend><a href="#">Lost password?</a></legend>
					<p class="input-with-button">
						<label for="recovery-mail">Enter your e-mail address</label>
						<input type="text" name="recovery-mail" id="recovery-mail" value="">
						<button type="button">Send</button>
					</p>
				</fieldset>
			</form>
			-->
		</div></div>
	</section>
