<?php

$assetLoader = Skyseek_Asset_Loader::getInstance();
$assetLoader->setAssetPath('/skins/admin/assets');
$assetLoader->compressAssets(false);


$assetLoader->addCss('reset');
$assetLoader->addCss('common');
$assetLoader->addCss('form');
$assetLoader->addCss('standard');
$assetLoader->addCss('960.gs.fluid');
$assetLoader->addCss('simple-lists');
$assetLoader->addCss('block-lists');
$assetLoader->addCss('planning');
$assetLoader->addCss('table');
$assetLoader->addCss('calendars');
$assetLoader->addCss('wizard');
$assetLoader->addCss('gallery');

$assetLoader->addJs('html5');
$assetLoader->addJs('jquery-1.4.2.min');
$assetLoader->addJs('common');
$assetLoader->addJs('standard');
$assetLoader->addJs('jquery.tip');
$assetLoader->addJs('list');
$assetLoader->addJs('jquery.modal');
$assetLoader->addJs('gtw/admin');
$assetLoader->addJs('searchField');

//Default Styles/Icons
//$this->headLink()->appendStylesheet('/skins/admin/assets/css/mini.php?files=reset,common,form,standard,960.gs.fluid,simple-lists,block-lists,table');

$this->headLink()->headLink(array('rel' => 'shortcut', 'href' => '/favicon.ico'));
$this->headLink()->headLink(array('rel' => 'icon', 'href' => '/favicon-large.png'));


$user = GTW_Service_User::getInstance()->getCurrentUser();

?>
<!DOCTYPE html>
<html lang="en">
<head>

	<?= $this->headTitle(); ?>

	<!-- Global stylesheets -->
	<?= $assetLoader->getCss(); ?>





	<!-- Charts library 
	<script type="text/javascript" src="http://www.google.com/jsapi"></script>
	<script type="text/javascript">

		// Load the Visualization API and the piechart package.
		google.load('visualization', '1', {'packages':['corechart']});

	</script>
	-->

</head>

<body>
<!-- The template uses conditional comments to add wrappers div for ie8 and ie7 - just add .ie or .ie7 prefix to your css selectors when needed -->
<!--[if lt IE 9]><div class="ie"><![endif]-->
<!--[if lt IE 8]><div class="ie7"><![endif]-->

	<!-- Header -->

	<!-- Server status -->
	<header>
		<div class="container_12">
			<div class="server-info">Version: <strong><?=GTW_VERSION;?></strong></div>
		</div>
	</header>
	<!-- End server status -->

	<!-- Main nav -->
	<nav id="main-nav">
		<ul class="container_12">
			<li class="home current"><a href="/admin/" title="Admin">Admin</a>
				<ul>
					<li class="with-menu"><a href="#" title="Give to Win settings">Settings</a>
						<div class="menu">
							<img src="/skins/admin/assets/img/menu-open-arrow.png" width="16" height="16">
							<ul>
								<li class="icon_address"><a href="#">Charities</a>
									<ul>
										<li class="icon_edit"><a href="/admin/charities/create">Create Charity</a></li>
										<li class="icon_search"><a href="/admin/charities/browse">Browse Charities</a></li>
									</ul>
								</li>
								<li class="icon_address"><a href="#">Cities</a>
									<ul>
										<li class="icon_edit"><a href="/admin/cities/create">Create City</a></li>
										<li class="icon_search"><a href="/admin/cities/browse">Browse Cities</a></li>
									</ul>
								</li>
								<li class="icon_address"><a href="#">Companies</a>
									<ul>
										<li class="icon_edit"><a href="/admin/companies/create">Create Company</a></li>
										<li class="icon_search"><a href="/admin/companies/browse">Browse Companies</a></li>
									</ul>
								</li>
								<li class="icon_address"><a href="/admin/email">Email</a>
									<ul>
										<li class="icon_search"><a href="/admin/email/browse-templates">Templates</a></li>
									</ul>
								</li>
								<li class="icon_address"><a href="#">Users</a>
									<ul>
										<li class="icon_search"><a href="/admin/users/browse">Browse Users</a></li>
									</ul>
								</li>
								
							</ul>
						</div>
					</li>
				</ul>
			</li>
			<!--
			<li class="users"><a href="#" title="Users">Users</a>
				<ul>
					<li><a href="#" title="Browse">Browse Users</a></li>
					<li><a href="#" title="Add user">Add New User</a></li>
				</ul>
			</li>
			<li class="stats"><a href="#" title="Redemptions">Redemptions</a></li>
			-->
		</ul>
	</nav>
	<!-- End main nav -->

	<!-- Sub nav -->
	<div id="sub-nav"><div class="container_12">

		<a href="#" title="Help" class="nav-button"><b>Help</b></a>

		<form id="search-form" name="search-form" method="post" action="/admin/index/search">
			<input type="text" name="s" id="s" value="" title="Search admin..." autocomplete="off">
		</form>

	</div></div>
	<!-- End sub nav -->

	<!-- Status bar -->
	<div id="status-bar"><div class="container_12">

		<ul id="status-infos">
			<li class="spaced">Logged as: <strong><?=$user->first_name;?> <?=$user->last_name;?></strong></li>

			<li><a href="/admin/auth/logout" class="button red" title="Logout"><span class="smaller">LOGOUT</span></a></li>
		</ul>

		<? if(count($this->breadCrumbs)): ?>
			<ul id="breadcrumb">
				<? foreach($this->breadCrumbs as $bc): ?>
					<li><a href="<?=$bc['url']?>" title="<?=$bc['title']?>"><?=$bc['title']?></a></li>
				<? endforeach;?>
			</ul>
		<? endif; ?>

	</div></div>
	<!-- End status bar -->

	<div id="header-shadow"></div>

	<? if($this->controlBar): ?>
		<?=$this->controlBar;?>
	<? endif;?>

	<!-- End header -->




	<!-- Content -->
	<article class="container_12">
		<?= $this->layout()->content; ?>
	</article>

	<!-- End content -->

	<footer>

		<div class="float-left">
			<a href="/admin/help/" class="button">Help</a>
			<a href="#" onclick="openAboutPrompt()" class="button">About</a>		</div>

		<div class="float-right">
			<a href="#top" class="button"><img src="/skins/admin/assets/img/icons/fugue/navigation-090.png" width="16" height="16"> Page top</a>		</div>

</footer>

		<!--[if lt IE 8]></div><![endif]-->
		<!--[if lt IE 9]></div><![endif]-->
		<?= $assetLoader->getJs(); ?>
	</body>
</html>