<?php

//Default Styles/Icons
$this->headLink()->appendStylesheet('/skins/admin/assets/css/mini.php?files=reset,common,form,standard,960.gs.fluid,simple-lists,block-lists,table');

$this->headLink()->headLink(array('rel' => 'shortcut', 'href' => '/favicon.ico'));
$this->headLink()->headLink(array('rel' => 'icon', 'href' => '/favicon-large.png'));


//In Reverse Order
$this->headScript()->prependFile(
    '/skins/admin/assets/js/standard-ie.js',
    'text/javascript',
    array('conditional' => 'lt IE 8')
);

$this->headScript()->prependFile('/skins/admin/assets/js/mini.php?files=html5,jquery-1.4.2.min,common,standard,jquery.tip.js,list');


//Default Styles/Icons
//$this->headLink()->appendStylesheet('/assets/css/reset.css');
//$this->headLink()->appendStylesheet('/assets/css/common.css');
//$this->headLink()->appendStylesheet('/assets/css/form.css');
//$this->headLink()->appendStylesheet('/assets/css/standard.css');
//$this->headLink()->appendStylesheet('/assets/css/960.gs.fluid.css');
//$this->headLink()->appendStylesheet('/assets/css/simple-lists.css');
//$this->headLink()->appendStylesheet('/assets/css/block-lists.css');
//$this->headLink()->appendStylesheet('/assets/css/planning.css');
//$this->headLink()->appendStylesheet('/assets/css/table.css');
//$this->headLink()->appendStylesheet('/assets/css/calendars.css');
//$this->headLink()->appendStylesheet('/assets/css/wizard.css');
//$this->headLink()->appendStylesheet('/assets/css/gallery.css');
//$this->headLink()->headLink(array('rel' => 'shortcut', 'href' => '/favicon.ico'));
//$this->headLink()->headLink(array('rel' => 'icon', 'href' => '/favicon-large.png'));

//In Reverse Order
//$this->headScript()->prependFile(
//    '/assets/js/standard-ie.js',
//    'text/javascript',
//    array('conditional' => 'lt IE 8')
//);

//$this->headScript()->prependFile('/assets/js/list.js');
//$this->headScript()->prependFile('/assets/js/jquery.datepick/jquery.datepick.min.js');
//$this->headScript()->prependFile('/assets/js/jquery.dataTables.min.js');
//$this->headScript()->prependFile('/assets/js/jquery.modal.js');
//$this->headScript()->prependFile('/assets/js/jquery.contextMenu.js');
//$this->headScript()->prependFile('/assets/js/jquery.hashchange.js');
//$this->headScript()->prependFile('/assets/js/jquery.accessibleList.js');
//$this->headScript()->prependFile('/assets/js/jquery.tip.js');
//$this->headScript()->prependFile('/assets/js/standard.js');
//$this->headScript()->prependFile('/assets/js/common.js');
//$this->headScript()->prependFile('/assets/js/old-browsers.js');
//$this->headScript()->prependFile('/assets/js/jquery-1.4.2.min.js');
//$this->headScript()->prependFile('/assets/js/html5.js');

?>
<!DOCTYPE html>
<html lang="en">
<head>

	<?= $this->headTitle(); ?>

	<!-- Global stylesheets -->
	<?= $this->headLink(); ?>





	<!-- Charts library -->
	<!--Load the AJAX API-->
	<script type="text/javascript" src="http://www.google.com/jsapi"></script>
	<script type="text/javascript">

		// Load the Visualization API and the piechart package.
		google.load('visualization', '1', {'packages':['corechart']});

	</script>


	<script type="text/javascript">

		// Demo modal
		function openModal()
		{
			$.modal({
				content: '<p>Gift Certificates Pro was created to as easy to use as powerful to use as possible. </p>',
				title: 'About GC',
				maxWidth: 500,
				buttons: {
					'Close': function(win) { win.closeModal(); }
				}
			});
		}


	</script>

</head>

<body>
<!-- The template uses conditional comments to add wrappers div for ie8 and ie7 - just add .ie or .ie7 prefix to your css selectors when needed -->
<!--[if lt IE 9]><div class="ie"><![endif]-->
<!--[if lt IE 8]><div class="ie7"><![endif]-->

	<!-- Header -->

	<!-- Server status -->
	<header>
		<div class="container_12">
			<div class="server-info">GTW Version: <strong>0.9</strong></div>
			<div class="server-info">Rev: <strong>1</strong></div>
		</div>
	</header>
	<!-- End server status -->

	<!-- Main nav -->
	<nav id="main-nav">
		<ul class="container_12">
			<?=$this->navCategory('home', 'Admin', '/admin/')?>
				<ul>
					<?=$this->navLink('dashboard', 'Dashboard', '/admin/email/browse-templates');?>
				</ul>
			</li>
			<?=$this->navCategory('email', 'Email', '/admin/email/')?>
				<ul>
					<?=$this->navLink('emailTemplates', 'Templates', '/admin/email/browse-templates');?>
				</ul>
			</li>
			<!--
			<li class="users"><a href="#" title="Users">Users</a>
				<ul>
					<li><a href="#" title="Browse">Browse Users</a></li>
					<li><a href="#" title="Add user">Add New User</a></li>
				</ul>
			</li>
			<li class="stats"><a href="#" title="Redemptions">Redemptions</a></li>
			-->
		</ul>
	</nav>
	<!-- End main nav -->

	<!-- Sub nav -->
	<div id="sub-nav"><div class="container_12">

		<a href="#" title="Help" class="nav-button"><b>Help</b></a>

		<form id="search-form" name="search-form" method="post" action="search.html">
			<input type="text" name="s" id="s" value="" title="Search admin..." autocomplete="off">
		</form>

	</div></div>
	<!-- End sub nav -->

	<!-- Status bar -->
	<div id="status-bar"><div class="container_12">

		<ul id="status-infos">
			<li class="spaced">Logged as: <strong>Admin</strong></li>

			<li><a href="/system/user/logout" class="button red" title="Logout"><span class="smaller">LOGOUT</span></a></li>
		</ul>

		<? if(count($this->breadCrumbs)): ?>
			<ul id="breadcrumb">
				<? foreach($this->breadCrumbs as $bc): ?>
					<li><a href="<?=$bc['url']?>" title="<?=$bc['title']?>"><?=$bc['title']?></a></li>
				<? endforeach;?>
			</ul>
		<? endif; ?>

	</div></div>
	<!-- End status bar -->

	<div id="header-shadow"></div>
	<!-- End header -->



	<!-- Content -->
	<article class="container_12">
		<?= $this->layout()->content; ?>
	</article>

	<!-- End content -->

	<footer>

		<div class="float-left">
			<a href="#" class="button">Help</a>
			<a href="#" onclick="openModal()" class="button">About</a>		</div>

		<div class="float-right">
			<a href="#top" class="button"><img src="/assets/img/icons/fugue/navigation-090.png" width="16" height="16"> Page top</a>		</div>

</footer>

		<!--[if lt IE 8]></div><![endif]-->
		<!--[if lt IE 9]></div><![endif]-->
		<?= $this->headScript(); ?>
	</body>
</html>