<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Give to Win');
echo $this->doctype();

?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>

		<link href="/skins/default/css/style.css" type="text/css" rel="stylesheet" />
		<link href="/skins/default/css/uni-form.css" type="text/css" rel="stylesheet" />
		<link href="/skins/default/css/gtw.uni-form.css" type="text/css" rel="stylesheet" />
		
		<!--[if gt IE 6]>
			<link href="/skins/default/css/ie.css" type="text/css" rel="stylesheet" />
		<![endif]-->

		<!-- MooTools! -->
		<script src="/skins/default/js/mootools.js" type="text/javascript"></script>

		<!-- Give To Win! -->
		<script src="/skins/default/js/givetowin.js" type="text/javascript"></script>

		<!-- Share Buttons
		<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
		<script type="text/javascript">stLight.options({publisher:'c2bd8b17-a3e0-4951-b0b6-d6a358e90643'});</script>
		-->


		<!-- Media Box Requirment -->
		<link rel="stylesheet" href="/skins/default/css/mediaboxAdvBlack21.css" type="text/css" media="screen" />
		<script src="/skins/default/js/mediaboxAdv-1.3.4b.js" type="text/javascript"></script>


		
		
	</head>
	<body>
		<div class="wrapper" style="height:600px;">
			<div id="outer_main">
				<div id="inner_main">
					<div class="page_title" style="padding-top:150px;">
						<center>
							<table cellpadding="0" cellspacing="0">
								<tr>
									<td class="left"><a href='/info/about'><img src="/skins/default/image/v2/logo_primary_white.png" /></a></td>
<?php if (isset($this->city->city)): ?>
										<td style="padding-top: 10px;">in</td>
										<td class="city_name"><?php echo $this->city->city; ?></td>
<?php endif; ?>
								</tr>
							</table>
						</center>
					</div>
					<div class="main-content" style="width:100%">
						<?php echo $this->layout()->content; ?>
					</div>
				</div>

			</div>
		</div>
		<div id="fb-root"></div>
		<!-- Facebook -->
		<script src="http://connect.facebook.net/en_US/all.js#appId=146287428751318&amp;xfbml=1"></script>
		<script>
			FB.init({
				appId  : '146287428751318',
				status : true, // check login status
				cookie : true, // enable cookies to allow the server to access the session
				xfbml  : false  // parse XFBML
			});
		</script>
	</body>
</html>
