<?php
$this->headTitle('Coming Soon!');
?>

<div class="content-box" style="width:820px;">
	<table width="100%" cellpadding="0" cellspacing="0" border="0">
		<tr class="header">
			<td class="left"></td>
			<td class="center" width="802"></td>
			<td class="right"></td>
		</tr>
		<tr>
			<td class="title" colspan="3" style="padding:20px; padding-bottom:0px; font-size: 8pt;">
				
				<br /><br />
				<h1>We're sorry but there are not yet any Give to Win Goals in <?=$this->city->city;?></h1>
			</td>
		</tr>
		<tr>
			<td colspan="3" class="body" style="padding:20px; padding-top:10px; font-size:10pt;">
				<p>Please subscribe to receive alerts for when we do. If you want to bring Give to Win to your city, you can help us out by:
				<br /><br />
				<ul>
					<li><a href="/Suggest/City">suggest a city</a></li>
					<li><a href="/Suggest/Charity">suggest a nonprofit</a></li>
					<li><a href="/Suggest/Company">suggest a business</a></li>
				</ul><br /><br />
				Thanks!</p><br />
			</td>
		</tr>
	</table>
</div>