<?php

$this->category = 'email';
$this->page = 'browseEmailTemplates';

$this->breadCrumbs = array(
	array('title'=>'Admin', 'url'=>'/admin'),
	array('title'=>'Email', 'url'=>'/admin/email'),
	array('title'=>'Templates', 'url'=>'/admin/email/browse-templates')
);

?>

<section class="grid_12">
	<div class="block-border"><form class="block-content form" id="table_form" method="post" action="">

			<h1>Email Templates</h1>

		<div class="block-controls">


		</div>

		<div class="no-margin"><table class="table" cellspacing="0" width="100%">

			<thead>
				<tr>
					<th scope="col" width="50">
						ID
					</th>
					<th scope="col">
						Name
					</th>
					<th scope="col">
						Subject
					</th>
					<th scope="col" width="100" class="table-actions">Actions</th>
				</tr>
			</thead>

			<tbody>
				<? foreach($this->templates as $template): ?>
				<tr>
					<td><?=$template->id;?></td>
					<td><a href="/admin/email/edit-template/id/<?=$template->id;?>"><b><?=$template->name;?></b></a></td>
					<td><?=$template->subject;?></td>
					<td class="table-actions">
						<a href="/admin/email/preview-template/id/<?=$template->id;?>" title="Preview" class="with-tip"><img src="/skins/admin/assets/img/icons/fugue/magnifier.png" width="16" height="16"></a>
						<a href="/admin/email/edit-template/id/<?=$template->id;?>" title="Edit" class="with-tip"><img src="/skins/admin/assets/img/icons/fugue/pencil.png" width="16" height="16"></a>
					</td>
				</tr>
				<? endforeach;?>


			</tbody>

		</table></div>

		<ul class="message no-margin">
			<li>Results 1 - <?=count($this->templates);?> out of <?=count($this->templates);?></li>
		</ul>


	</form></div>
</section>