<?php

$this->category = 'email';
$this->page = 'browseEmailTemplates';

$this->breadCrumbs = array(
	array('title'=>'Admin', 'url'=>'/admin'),
	array('title'=>'Email', 'url'=>'/admin/email'),
	array('title'=>'Templates', 'url'=>'/admin/email/browse-templates')
);

?>

<section class="grid_12">
	<div class="block-border"><form class="block-content form" id="table_form" method="post" action="">


		<div class="block-controls">


		</div>

		<div class="no-margin"><table class="table" cellspacing="0" width="100%">

			<thead>
				<tr>
					<th scope="col" width="50">
						ID
					</th>
					<th scope="col">
						Subject
					</th>
					<th scope="col" width="50" class="table-actions">Actions</th>
				</tr>
			</thead>

			<tbody>

				<tr>
					<td>123</td>
					<td>Lorem ipsum sit amet</td>
					<td class="table-actions">
						<a href="#" title="Preview" class="with-tip"><img src="/skins/admin/assets/img/icons/fugue/magnifier.png" width="16" height="16"></a>
						<a href="#" title="Edit" class="with-tip"><img src="/skins/admin/assets/img/icons/fugue/pencil.png" width="16" height="16"></a>
					</td>
				</tr>
				<tr>
					<td>123</td>
					<td>Lorem ipsum sit amet</td>
					<td class="table-actions">
						<a href="#" title="Preview" class="with-tip"><img src="/skins/admin/assets/img/icons/fugue/magnifier.png" width="16" height="16"></a>
						<a href="#" title="Edit" class="with-tip"><img src="/skins/admin/assets/img/icons/fugue/pencil.png" width="16" height="16"></a>
					</td>
				</tr>
				<tr>
					<td>123</td>
					<td>Lorem ipsum sit amet</td>
					<td class="table-actions">
						<a href="#" title="Preview" class="with-tip"><img src="/skins/admin/assets/img/icons/fugue/magnifier.png" width="16" height="16"></a>
						<a href="#" title="Edit" class="with-tip"><img src="/skins/admin/assets/img/icons/fugue/pencil.png" width="16" height="16"></a>
					</td>
				</tr>
				<tr>
					<td>123</td>
					<td>Lorem ipsum sit amet</td>
					<td class="table-actions">
						<a href="#" title="Preview" class="with-tip"><img src="/skins/admin/assets/img/icons/fugue/magnifier.png" width="16" height="16"></a>
						<a href="#" title="Edit" class="with-tip"><img src="/skins/admin/assets/img/icons/fugue/pencil.png" width="16" height="16"></a>
					</td>
				</tr>


			</tbody>

		</table></div>

		<ul class="message no-margin">
			<li>Results 1 - 5 out of 23</li>
		</ul>


	</form></div>
</section>