<?php
$this->headTitle('About Us');
?>



<div class="content-box" style="width:820px;">
	<table width="100%" cellpadding="0" cellspacing="0" border="0">
		<tr class="header">
			<td class="left"></td>
			<td class="center" width="802"></td>
			<td class="right"></td>
		</tr>
		<tr>
			<td class="title" colspan="3" style="padding:20px;">
				<h1>About Us</h1>
			</td>
		</tr>
		<tr>
			<td colspan="3" class="body" style="padding:20px; font-size: 10pt;">
				<p>Founded in August of 2010 and based out of Atlanta, Give to Win is an online community network that allows visitors to support local nonprofits solving issues that are important to them. When you give to these organizations, local businesses show their support by offering you special deals.</p>
				<br />
				<p>Give to Win grew out of a desire to help others and to help others support their community. With the help of many people, it has grown into something much bigger. We founded Give to Win on four ideas.</p>
				<br />
				<b style="font-size: 12pt; color: white;">Take something good and make it better.</b>
				<br />
				<p>Everybody wants to give, but these days most of us need to save. So why not do both? When you donate to a nonprofit’s goal through Give to Win, a local business will thank you with a discount voucher if the goal is met.</p>
				<br />
				<p>Give to your community, Give to yourself.</p>
				<br />
				<b style="font-size: 12pt; color: white;">Support responsible business.</b>
				<p>Give to Win is a registered 501(c)3 non-profit website and we are committed to supporting corporate social responsibility and nonprofit organizations working in your community. We target socially engaged businesses so you can pursue a socially conscious lifestyle that is both rewarding and reasonably priced.</p>
				<br />
				<b style="font-size: 12pt; color: white;">Bridge the gap.</b>
				<p>Give To Win connects you with great local and regional charitable organizations working in your community. When they are featured on the site you can find out about what they do and how you can help, and when it’s over you can keep tabs on their work through our network.</p>
				<br />
				<b style="font-size: 12pt; color: white;">Do it right.</b>
				<p>Customer satisfaction is critical to us and we always have your interests in mind. When you donate through Give to Win, all your money goes to charity. Not five percent, not fifty percent…100%. Give to Win is committed to its charitable goals and is interested in making change instead of just profits. Simply put, we do it right.</p>
				<br />
				<br />
				<h1>Head Staff</h1>
				<br />
				<dl>
					<dt><b>Maxwell Ruppersburg</b></dt>
					<dd><i>Founder</i></dd>
					<br />
					<dt><b>Jacob Parnell</b></dt>
					<dd></dd>
					<br />
					<dt><b>Anand Agrawal</b></dt>
					<dd></dd>
				</dl>
				<br /><br />
				<p>If you ever have any suggestions or if anything is ever unsatisfactory, please feel free to contact us at <a href="mailto:customerservice@givetowin.org">customerservice@givetowin.org</a>.</p>

			</td>
		</tr>
	</table>
</div>