<?php
$this->headTitle('Contact Us');
?>

<table cellpadding="0" cellspacing="0">
	<tr>
		<td width="590" valign="top">
			<div class="content-box" style="width:820px;" id="step1">
				<table width="100%" cellpadding="0" cellspacing="0" border="0">
					<tr class="header">
						<td class="left"></td>
						<td class="center" width="802"></td>
						<td class="right"></td>
					</tr>
					<tr>
						<td colspan="3" class="body">
							<?php echo $this->form;?>
						</td>
					</tr>
				</table>
			</div>
        </td>
    </tr>
</table>

<script type="text/javascript">
	$(document).ready(function(){
		$('form.uniForm').uniform();
	});
</script>
