<?php
$this->headTitle('Frequently Asked Questions');
?>

<style>

hr {
	border: 1px dotted #ccc;
}

</style>


<div class="content-box" style="width:820px;">
	<table width="100%" cellpadding="0" cellspacing="0" border="0">
		<tr class="header">
			<td class="left"></td>
			<td class="center" width="802"></td>
			<td class="right"></td>
		</tr>
		<tr>
			<td class="title" colspan="3" style="padding:20px;">
				<h1>Frequently Asked Questions</h1>
			</td>
		</tr>
		<tr>
			<td colspan="3" class="body" style="padding:20px;">
				<h3>I like today's deal - how do I get it?</h3><br />
				Just click the big “G” on the goal page before the offer ends. We process your donation and if the fundraising goal is met, we’ll send you a link to print your GTW voucher. If not enough people give, no one wins (but you’ve still made a donation), so invite your friends to make sure you get the deal!
				<br /><br />
				<hr /><br />
				<h3>Do I have to get a group of people I know to donate if I want to get the reward voucher?</h3><br />
				Nope. The fundraising goal can be accomplished with the generosity of any of our subscribers, but you can help ensure you get the voucher by telling your friends or others, so spread the word!  Give to Win is a great option for the givers and the savers in your life.
				<br /><br /><hr /><br />
				<h3>What happens if the fundraising goal isn’t met?</h3><br />
				If not enough people give and the goal isn’t met, then no vouchers will be rewarded, but the organization will still receive your donation. Make sure to tell your friends about the cause and everybody wins!
				<br /><br /><hr /><br />
				<h3>Do I need to use my GTW voucher the same day I buy it?</h3><br />
				No, most vouchers cannot be used until the day after your purchase.
				<br /><br /><hr /><br />
				<h3>I made a donation and received a voucher- how do I use it?</h3><br />
				Once the goal is met, you'll receive an email with a link to sign in and print your voucher. The voucher has redemption instructions and directions to help you find it!
				<br /><br /><hr /><br />
				<h3>Can I make a donation in someone else’s name?</h3><br />
				Yes of course!  When you make a donation in someone else’s name, you will get the good karma but they’ll get the voucher. It’s just like sending a gift!  So unless the Fine Print specifically states otherwise, spread the love! To have us send them the gift voucher, select the gift option at checkout.
				<br /><br /><hr /><br />
				<h3>Wait, my name is on the voucher. Are you sure I can use this as a gift?</h3><br />
				Yes!  We tell the businesses that we work with that customers may receive vouchers as gifts for others.
				<br /><br /><hr /><br />
				<h3>If I don't use the full value of the GTW voucher in one visit, can I use the remainder later?</h3><br />
				No. Unless otherwise stated you do not receive store credit or cash back for whatever you don't use. Bring a friend - share a little!
				<br /><br /><hr /><br />
				<h3>Can I combine my voucher with other offers or specials?</h3><br />
				No, not unless the voucher specifically states otherwise.
				<br /><br /><hr /><br />
				<h3>Am I billed as soon as I make a donation?</h3><br />
				Yes.  As soon as you make a donation your card will be charged.  If the goal isn’t met, your money still goes to the featured organization.  If you want to cancel your donation you can contact us at customerservice@givetowin.org and we’ll handle it straight away!
				<br /><br /><hr /><br />
				<h3>Is Give to Win safe?</h3><br />
				Extremely. Your credit card number is transmitted by SSL directly to a secure electronic vault. At no time is your credit card information stored on our servers.
				<br /><br /><hr /><br />
				<h3>Can I return a GTW voucher?</h3><br />
				Read about our return policy here.
				<br /><br /><hr /><br />
				<h3>What happens if my coupon expires?</h3><br />
				All is not lost! Once a coupon reaches its expiration date, it loses its promotional value, but you can still redeem it at the price you paid for the length of time stated by gift certificate laws in your state.
			</td>
		</tr>
	</table>
</div>
