<?php
$this->headTitle('Jobs');
?>



<div class="content-box" style="width:820px;">
	<table width="100%" cellpadding="0" cellspacing="0" border="0">
		<tr class="header">
			<td class="left"></td>
			<td class="center" width="802"></td>
			<td class="right"></td>
		</tr>
		<tr>
			<td class="title" colspan="3" style="padding:20px;">
				<h1>Jobs</h1>
			</td>
		</tr>
		<tr>
			<td colspan="3" class="body" style="padding:20px; font-size: 10pt;">
				<p>We are currently not hiring at the moment.</p>
				<br />
			</td>
		</tr>
	</table>
</div>