<?php

$this->category = 'users';
$this->page = 'browseUsers';

$this->breadCrumbs = array(
	array('title'=>'Admin', 'url'=>'/admin'),
	array('title'=>'Users', 'url'=>'/admin/users'),
	array('title'=>'Browse', 'url'=>'/admin/users/browse')
);

?>

<?php $this->headScript()->captureStart() ?>
	function openModalDelete(id)
	{
		console.log(id);
		$.modal({
			content: '<p>This user, all there subscriptions, coupons, comments will be deleted.</p>'+
				  '<ul class="simple-list with-icon">'+
				  '    <li><a href="/admin/users/delete-user/id/'+id+'">Yes, Permanently Delete User</a></li>'+
				  '</ul>',
			title: 'Are you sure you want to delete this user?',
			maxWidth: 500,
			buttons: {
				'Cancel': function(win) { win.closeModal(); }
			}

		});
	}
<?php $this->headScript()->captureEnd() ?>

		<section class="grid_12">
			<div class="block-border"><form class="block-content form" id="table_form" method="post" action="">
				<h1>Users</h1>
				<div class="block-controls">					
						<?php echo $this->paginationControl($this->users, 'Elastic', 'paginatorHeader.phtml'); ?>
				</div>			
				<div class="no-margin"><table class="table" cellspacing="0" width="100%">				
					<thead>
						<tr>
							<th scope="col">ID</th>
							<th scope="col">First Name</th>
							<th scope="col">Last Name</th>
							<th scope="col">Email</th>
							<th scope="col">Status</th>
							<th scope="col">Actions</th>
						</tr>
					</thead>					
					<tbody>			
						<? foreach($this->users as $user):?>			
						<tr>
							<td><?=$user->id;?></td>
							<td><?=$user->first_name;?></td>
							<td><?=$user->last_name;?></td>
							<td><?=$user->email;?></td>
							<td><?=$user->status->status;?></td>
							<td class="table-actions">
								<a href="/admin/users/edit/id/<?=$user->id;?>" title="Edit" class="with-tip"><img src="/skins/admin/assets/img/icons/fugue/user-edit.png" width="16" height="16"></a>
								<a href="#" onClick="openDeleteUserPrompt(<?=$user->id;?>);" title="Delete" class="with-tip"><img src="/skins/admin/assets/img/icons/fugue/user-delete.png" width="16" height="16"></a>
							</td>
						</tr>
						<? endforeach; ?>						
					</tbody>				
				</table></div>				
				<?php echo $this->paginationControl($this->users, 'Elastic', 'paginatorFooter.phtml'); ?>
			</form></div>
		</section>
